version: "3.8"

services:
  application:
    container_name: docker-compose-whitemonday
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ENCRYPTION_SECRET_KEY=${ENCRYPTION_SECRET_KEY}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"

  database:
    container_name: whitemonday
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      retries: 10
