global:
  scrape_interval: 15s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: "spring-boot-apps"
    metrics_path: "/actuator/prometheus"
    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka
    relabel_configs:
      - source_labels: [__meta_eureka_instance_metadata_management_port]
        action: replace
        target_label: __metrics_path__
        regex: (.*)
        replacement: /actuator/prometheus
      - source_labels: [__meta_eureka_app_name]
        target_label: application

  - job_name: "gateway-service"
    static_configs:
      - targets: ["gateway-service:8000"]

  - job_name: "eureka-server"
    static_configs:
      - targets: ["eureka-server:8761"]
