server:
  port: 8081
spring:
  application:
    name: user-service
  config:
    import: "optional:file:./user-service/.env"
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  main:
    web-application-type: servlet
    log-startup-info: true
  cloud:
    compatibility-verifier:
      enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5000
    disable-delta: true
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.cloud: DEBUG
jwt:
  secret-key: ${JWT_SECRET_KEY}

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.mail.MailException
          - java.net.ConnectException
          - java.io.IOException
    instances:
      email-service:
        base-config: default
        max-attempts: 5
        wait-duration: 2s
        exponential-backoff-multiplier: 1.5
      database-operation:
        base-config: default
        max-attempts: 3
        wait-duration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health,retries,metrics